-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: SarkarverseSong/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes

CREATE TABLE /*_*/sarkarverse_songs (
  song_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  song_number VARCHAR(10) NOT NULL,
  song_date VARCHAR(20) NOT NULL,
  song_title VARCHAR(255) NOT NULL,
  song_theme VARCHAR(255) NOT NULL,
  song_language VARCHAR(100) NOT NULL,
  song_music VARCHAR(255) NOT NULL,
  song_page_id INT UNSIGNED NOT NULL,
  song_page_title VARCHAR(255) NOT NULL,
  PRIMARY KEY(song_id),
  UNIQUE INDEX idx_song_number (song_number),
  INDEX idx_song_theme (song_theme),
  INDEX idx_song_language (song_language),
  INDEX idx_song_page_id (song_page_id)
) /*$wgDBTableOptions*/;

CREATE TABLE /*_*/sarkarverse_song_categories (
  ssc_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  ssc_song_number VARCHAR(10) NOT NULL,
  ssc_category VARCHAR(255) NOT NULL,
  PRIMARY KEY(ssc_id),
  INDEX idx_ssc_song_number (ssc_song_number),
  INDEX idx_ssc_category (ssc_category),
  UNIQUE INDEX idx_ssc_unique (ssc_song_number, ssc_category)
) /*$wgDBTableOptions*/;
